// Generated by Wrangler by running `wrangler types`

interface Env {
	AI_GATEWAY_OPENAI_URL: string;
	AI_GATEWAY_GROQ_URL: string;
	OPENAI_API_KEY: string;
	GROQ_API_KEY: string;
	BETTER_AUTH_URL: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_DOMAIN: string;
	DO_CHAT_API_URL: string;
	CHAT_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").ChatDurableObject>;
	AGENT_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").AgentDurableObject>;
	DB: D1Database;
}
declare module "*.sql" {
	const value: string;
	export default value;
}