// Generated by Wrangler by running `wrangler types`

interface Env {
	ALLOWED_ORIGINS: string;
	CHAT_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").ChatDurableObject>;
	DB: D1Database;
}
declare module "*.sql" {
	const value: string;
	export default value;
}