// Generated by Wrangler by running `wrangler types`

interface Env {
	CHAT_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").ChatDurableObject>;
}
declare module "*.sql" {
	const value: string;
	export default value;
}