/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as appRouteImport } from './routes/(app)/route'
import { Route as IndexImport } from './routes/index'
import { Route as HomeLoginButtonImport } from './routes/home/LoginButton'
import { Route as HomeHomeImport } from './routes/home/Home'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthSigninImport } from './routes/auth/signin'
import { Route as appChatImport } from './routes/(app)/chat'
import { Route as appAgentsImport } from './routes/(app)/agents'

// Create/Update Routes

const appRouteRoute = appRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeLoginButtonRoute = HomeLoginButtonImport.update({
  id: '/home/LoginButton',
  path: '/home/LoginButton',
  getParentRoute: () => rootRoute,
} as any)

const HomeHomeRoute = HomeHomeImport.update({
  id: '/home/Home',
  path: '/home/Home',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any)

const appChatRoute = appChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => appRouteRoute,
} as any)

const appAgentsRoute = appAgentsImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => appRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRoute
    }
    '/(app)/agents': {
      id: '/(app)/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof appAgentsImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/chat': {
      id: '/(app)/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof appChatImport
      parentRoute: typeof appRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/home/Home': {
      id: '/home/Home'
      path: '/home/Home'
      fullPath: '/home/Home'
      preLoaderRoute: typeof HomeHomeImport
      parentRoute: typeof rootRoute
    }
    '/home/LoginButton': {
      id: '/home/LoginButton'
      path: '/home/LoginButton'
      fullPath: '/home/LoginButton'
      preLoaderRoute: typeof HomeLoginButtonImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface appRouteRouteChildren {
  appAgentsRoute: typeof appAgentsRoute
  appChatRoute: typeof appChatRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAgentsRoute: appAgentsRoute,
  appChatRoute: appChatRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof appRouteRouteWithChildren
  '/agents': typeof appAgentsRoute
  '/chat': typeof appChatRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/home/Home': typeof HomeHomeRoute
  '/home/LoginButton': typeof HomeLoginButtonRoute
}

export interface FileRoutesByTo {
  '/': typeof appRouteRouteWithChildren
  '/agents': typeof appAgentsRoute
  '/chat': typeof appChatRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/home/Home': typeof HomeHomeRoute
  '/home/LoginButton': typeof HomeLoginButtonRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/agents': typeof appAgentsRoute
  '/(app)/chat': typeof appChatRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/home/Home': typeof HomeHomeRoute
  '/home/LoginButton': typeof HomeLoginButtonRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/chat'
    | '/auth/signin'
    | '/auth/signup'
    | '/home/Home'
    | '/home/LoginButton'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/chat'
    | '/auth/signin'
    | '/auth/signup'
    | '/home/Home'
    | '/home/LoginButton'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(app)/agents'
    | '/(app)/chat'
    | '/auth/signin'
    | '/auth/signup'
    | '/home/Home'
    | '/home/LoginButton'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  HomeHomeRoute: typeof HomeHomeRoute
  HomeLoginButtonRoute: typeof HomeLoginButtonRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  HomeHomeRoute: HomeHomeRoute,
  HomeLoginButtonRoute: HomeLoginButtonRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(app)",
        "/auth/signin",
        "/auth/signup",
        "/home/Home",
        "/home/LoginButton"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(app)": {
      "filePath": "(app)/route.tsx",
      "children": [
        "/(app)/agents",
        "/(app)/chat"
      ]
    },
    "/(app)/agents": {
      "filePath": "(app)/agents.tsx",
      "parent": "/(app)"
    },
    "/(app)/chat": {
      "filePath": "(app)/chat.tsx",
      "parent": "/(app)"
    },
    "/auth/signin": {
      "filePath": "auth/signin.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/home/Home": {
      "filePath": "home/Home.tsx"
    },
    "/home/LoginButton": {
      "filePath": "home/LoginButton.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
